### ISSUE TITLE
New accounts fail to verify

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#406]
Issue reported via email by yurinai@gmail.com

----

Hi PyCon TW:

I created my account but cannot see an option to submit a proposal.

It shows "please verify your account". When clicked on link "Request a new one.", it shows 500 server error.

Please help let me know how to submit proposal for talk.

**Comment by uranusjr** [comment]
Looks like a SMTP setup problem

```
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/deploy/pycontw/venv/2018/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/deploy/pycontw/venv/2018/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/deploy/pycontw/venv/2018/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/deploy/pycontw/venv/2018/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/deploy/pycontw/venv/2018/lib/python3.6/site-packages/django/core/management/commands/sendtestemail.py", line 33, in handle
    recipient_list=kwargs['email'],
  File "/home/deploy/pycontw/venv/2018/lib/python3.6/site-packages/django/core/mail/__init__.py", line 62, in send_mail
    return mail.send()
  File "/home/deploy/pycontw/venv/2018/lib/python3.6/site-packages/django/core/mail/message.py", line 342, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/deploy/pycontw/venv/2018/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 107, in send_messages
    sent = self._send(message)
  File "/home/deploy/pycontw/venv/2018/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 123, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/home/deploy/.pyenv/versions/3.6.4/lib/python3.6/smtplib.py", line 888, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (554, b'Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-1: web@pycon.tw, PyCon Taiwan <web@pycon.tw>')
```

**Comment by uranusjr** [comment]
Now using Gmail directly for email. I don’t think we will send many emails anyway, so it should be fine. The account used is dev@pycon.tw. I have the password.
